package feed.bihar.repository;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.hibernate.annotations.CreationTimestamp;


@javax.persistence.Entity
public class Bene {
	private String name;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;//autogenerated PK 
	@Column(nullable = false, updatable = false)
	@CreationTimestamp
	
	private Date date;//current
	@CreationTimestamp
	private Date l_time;//current also at time of updating table
	private String mobile;
	private String address;
	private String status;
	
	
	
	public Date getL_time() {
		return l_time;
	}

	public void setL_time(Date l_time) {
		this.l_time = l_time;
	}

	public Bene() {
	}
	
	public Bene(String name, int id, Date date, Date l_time, String mobile, String address, String status) {
		super();
		this.name = name;
		this.id = id;
		this.date = date;
		this.l_time = l_time;
		this.mobile = mobile;
		this.address = address;
		this.status = status;
	}

	
	
	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getMobile() {
		return mobile;
	}
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public Date getDate() {
		return date;
	}
	public void setDate(Date date) {
		this.date = date;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	@Override
	public String toString() {
		return "Bene [name=" + name + ", id=" + id + ", date=" + date + ", l_time=" + l_time + ", mobile=" + mobile
				+ ", address=" + address + ", status=" + status + "]";
	}
	
	
	
	

}
